# Qiniu upload action for GitHub Actions
# https://github.com/qiniu/action-qiniu-upload
# This is a template. You need to set QINIU_AK, QINIU_SK, QINIU_BUCKET, QINIU_ZONE, QINIU_DEST_DIR as secrets in your repo.

name: Deploy site to Tencloud

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  upload-static-site:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install tencloud
        run: |
          npm install -g @cloudbase/cli
          tcb login --apiKeyId ${{ secrets.TENCENT_CLOUD_API_KEY }} --apiKey ${{ secrets.TENCENT_CLOUD_API_SECRET }}
      - name: Cloud Upload
        run: |
          tcb hosting deploy ./prototype /prototype -e lique-8gutx0qy1cd73fe2
